-- MySQL Script generated by MySQL Workbench
-- Wed May  8 23:17:55 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema main_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `main_database` ;

-- -----------------------------------------------------
-- Schema main_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `main_database` DEFAULT CHARACTER SET utf8 ;
USE `main_database` ;

-- -----------------------------------------------------
-- Table `main_database`.`Consumption_Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Consumption_Categories` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Consumption_Categories` (
  `id_Consumption_Category` INT NOT NULL AUTO_INCREMENT COMMENT 'Id категории расхода\n',
  `Name_Of_Category` VARCHAR(60) NOT NULL COMMENT 'Наиманование категории расхода',
  PRIMARY KEY (`id_Consumption_Category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Costs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Costs` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Costs` (
  `id_Document_Of_Consumption` INT NOT NULL COMMENT 'Документ расхода',
  `Date_Of_Cost` DATE NOT NULL COMMENT 'Дата расхода\n',
  `Amount` FLOAT NOT NULL COMMENT 'Сумма расхода\n',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения\n',
  `Consumption_Categories_id_Consumption_Category` INT NOT NULL COMMENT 'Категория расхода\n',
  `Types_Of_Payment_id_Of_Type` INT NOT NULL COMMENT 'Форма оплаты',
  `Periodicities_id_Periodicity` INT NOT NULL COMMENT 'Периодичность',
  `To` VARCHAR(60) NOT NULL,
  `From` VARCHAR(60) NOT NULL,
  INDEX `fk_Costs_Сonsumption_Сategories1_idx` (`Consumption_Categories_id_Consumption_Category` ASC),
  INDEX `fk_Costs_Types_Of_Paintment1_idx` (`Types_Of_Payment_id_Of_Type` ASC),
  INDEX `fk_Costs_Periodicities1_idx` (`Periodicities_id_Periodicity` ASC),
  PRIMARY KEY (`id_Document_Of_Consumption`),
  UNIQUE INDEX `Documents_Of_Consumption_id_Document_Of_Consumption_UNIQUE` (`id_Document_Of_Consumption` ASC),
  INDEX `fk_Costs_Employees1_idx` (`To` ASC),
  INDEX `fk_Costs_Employees2_idx` (`From` ASC),
  CONSTRAINT `fk_Costs_Сonsumption_Сategories1`
    FOREIGN KEY (`Consumption_Categories_id_Consumption_Category`)
    REFERENCES `main_database`.`Consumption_Categories` (`id_Consumption_Category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Costs_Types_Of_Paintment1`
    FOREIGN KEY (`Types_Of_Payment_id_Of_Type`)
    REFERENCES `main_database`.`Types_Of_Payment` (`id_Of_Type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Costs_Periodicities1`
    FOREIGN KEY (`Periodicities_id_Periodicity`)
    REFERENCES `main_database`.`Periodicities` (`id_Periodicity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Costs_Documents_Of_Consumption1`
    FOREIGN KEY (`id_Document_Of_Consumption`)
    REFERENCES `main_database`.`Documents_Of_Consumption` (`id_Document_Of_Consumption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Costs_Employees1`
    FOREIGN KEY (`To`)
    REFERENCES `main_database`.`Employees` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Costs_Employees2`
    FOREIGN KEY (`From`)
    REFERENCES `main_database`.`Employees` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Countries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Countries` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Countries` (
  `id_Country` INT NOT NULL AUTO_INCREMENT COMMENT 'Id страны',
  `Name_Of_Country` VARCHAR(60) NOT NULL COMMENT 'Наименование страны',
  PRIMARY KEY (`id_Country`),
  UNIQUE INDEX `Name_Of_Country_UNIQUE` (`Name_Of_Country` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Customer_Statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Customer_Statuses` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Customer_Statuses` (
  `id_Status` INT NOT NULL AUTO_INCREMENT COMMENT 'Id статуса клиента\n',
  `Name_of_status` VARCHAR(30) NOT NULL COMMENT 'Наименование статуса клиента\n',
  PRIMARY KEY (`id_Status`),
  UNIQUE INDEX `id_UNIQUE` (`id_Status` ASC),
  UNIQUE INDEX `Name_of_status_UNIQUE` (`Name_of_status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Customers` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Customers` (
  `id_Customer` INT NOT NULL AUTO_INCREMENT COMMENT 'Id клиента\n',
  `Name` VARCHAR(80) NOT NULL COMMENT 'Имя ',
  `Lastname` VARCHAR(80) NOT NULL COMMENT 'Фамилия',
  `Patronymic` VARCHAR(80) NULL COMMENT 'Отчество',
  `Address` VARCHAR(120) NOT NULL COMMENT 'Адрес',
  `Phone_Number` VARCHAR(20) NOT NULL COMMENT 'Телефон',
  `Nickname` VARCHAR(100) NOT NULL COMMENT 'Никнейм',
  `Birthday` DATE NULL COMMENT 'День рождения',
  `Passport_data` VARCHAR(20) NULL COMMENT 'Паспортные данные',
  `Size` VARCHAR(45) NOT NULL COMMENT 'Размер',
  `Parameters` VARCHAR(45) NOT NULL COMMENT 'Параметры',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  `Photo` MEDIUMBLOB NULL DEFAULT NULL COMMENT 'Фото клиента',
  `Customer_Statuses_id_Status` INT NOT NULL COMMENT 'Статус клиента',
  `Order_Channels_id_Channel` INT NOT NULL COMMENT 'Способ заказа\n',
  `Employees_id_Employee` INT NOT NULL COMMENT 'Сотрудик, работающий с клиентом',
  PRIMARY KEY (`id_Customer`),
  UNIQUE INDEX `id_Client_UNIQUE` (`id_Customer` ASC),
  INDEX `fk_Clients_Customer_Statuses1_idx` (`Customer_Statuses_id_Status` ASC),
  INDEX `fk_Clients_Order_Channels1_idx` (`Order_Channels_id_Channel` ASC),
  CONSTRAINT `fk_Clients_Customer_Statuses1`
    FOREIGN KEY (`Customer_Statuses_id_Status`)
    REFERENCES `main_database`.`Customer_Statuses` (`id_Status`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clients_Order_Channels1`
    FOREIGN KEY (`Order_Channels_id_Channel`)
    REFERENCES `main_database`.`Order_Channels` (`id_Channel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Customers_Balance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Customers_Balance` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Customers_Balance` (
  `Customers_id_Customer` INT NOT NULL COMMENT 'Клиент',
  `Accured` FLOAT NULL COMMENT 'Начислено',
  `Paid` FLOAT NULL COMMENT 'Оплачено',
  `Debt` FLOAT NULL COMMENT 'Долг',
  PRIMARY KEY (`Customers_id_Customer`),
  UNIQUE INDEX `Customers_id_Customer_UNIQUE` (`Customers_id_Customer` ASC),
  CONSTRAINT `fk_Customers_Balance_Customers1`
    FOREIGN KEY (`Customers_id_Customer`)
    REFERENCES `main_database`.`Customers` (`id_Customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Documents_Of_Consumption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Documents_Of_Consumption` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Documents_Of_Consumption` (
  `id_Document_Of_Consumption` INT NOT NULL AUTO_INCREMENT COMMENT 'Id документа расхода',
  `Default_Folder` VARCHAR(120) NOT NULL COMMENT 'Путь, в котором лежат подобные документы',
  `Name_Of_Document` VARCHAR(120) NOT NULL COMMENT 'Имя докумета',
  PRIMARY KEY (`id_Document_Of_Consumption`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Documents_Of_Receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Documents_Of_Receipts` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Documents_Of_Receipts` (
  `id_Document_Of_Receipt` INT NOT NULL AUTO_INCREMENT COMMENT 'Id документ поступления',
  `Default_Folder` VARCHAR(120) NOT NULL COMMENT 'Путь, где лежат подобные документы',
  `Name_Of_Document` VARCHAR(120) NOT NULL COMMENT 'Имя документа',
  PRIMARY KEY (`id_Document_Of_Receipt`),
  UNIQUE INDEX `id_Document_UNIQUE` (`id_Document_Of_Receipt` ASC),
  UNIQUE INDEX `Name_Of_Document_UNIQUE` (`Name_Of_Document` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Employee_Positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Employee_Positions` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Employee_Positions` (
  `id_Employee_Position` INT NOT NULL AUTO_INCREMENT COMMENT 'Id должности сотрудника',
  `Name_Of_Position` VARCHAR(60) NOT NULL COMMENT 'Наименование должности',
  PRIMARY KEY (`id_Employee_Position`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Employee_Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Employee_Roles` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Employee_Roles` (
  `id_Employee_Role` INT NOT NULL AUTO_INCREMENT COMMENT 'Id роли сотрудинка',
  `Name_Of_Role` VARCHAR(60) NOT NULL COMMENT 'Наименование роли',
  PRIMARY KEY (`id_Employee_Role`),
  UNIQUE INDEX `Name_Of_Role_UNIQUE` (`Name_Of_Role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Employees` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Employees` (
  `Login` VARCHAR(60) NOT NULL COMMENT 'Логин',
  `Password` VARCHAR(60) NOT NULL COMMENT 'Пароль',
  `Name` VARCHAR(40) NOT NULL COMMENT 'Имя\n',
  `Lastname` VARCHAR(80) NOT NULL COMMENT 'Фамилия',
  `Patronymic` VARCHAR(60) NULL COMMENT 'Отчество',
  `Phone_Number` VARCHAR(20) NOT NULL COMMENT 'Телефон',
  `Email` VARCHAR(80) NOT NULL COMMENT 'Электронная почта',
  `Passport_Data` VARCHAR(45) NOT NULL COMMENT 'Паспортные данные',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  `Photo` MEDIUMBLOB NULL DEFAULT NULL COMMENT 'Фото',
  `Added` DATE NOT NULL COMMENT 'Дата добавления',
  `Last_Salary` FLOAT NULL COMMENT 'Начисленная з/п за работу в последний месяц',
  `Employee_Roles_id_Employee_Role` INT NOT NULL COMMENT 'Роль сотрудиника',
  `Employee_Positions_id_Employee_Position` INT NOT NULL COMMENT 'Должность сотрудника',
  PRIMARY KEY (`Login`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  INDEX `fk_Employees_Employee_Roles1_idx` (`Employee_Roles_id_Employee_Role` ASC),
  INDEX `fk_Employees_Employee_Positions1_idx` (`Employee_Positions_id_Employee_Position` ASC),
  CONSTRAINT `fk_Employees_Employee_Roles1`
    FOREIGN KEY (`Employee_Roles_id_Employee_Role`)
    REFERENCES `main_database`.`Employee_Roles` (`id_Employee_Role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_Employee_Positions1`
    FOREIGN KEY (`Employee_Positions_id_Employee_Position`)
    REFERENCES `main_database`.`Employee_Positions` (`id_Employee_Position`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Fittings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Fittings` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Fittings` (
  `Customers_id_Customer` INT NOT NULL COMMENT 'Клиент',
  `Orders_id_Order` INT NOT NULL COMMENT 'Заказ',
  `Date` DATE NOT NULL COMMENT 'Дата',
  `Time` TIME NOT NULL COMMENT 'Время',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  `Types_Of_Fitting_id_Type_Of_Fitting` INT NOT NULL COMMENT 'Тип примерки',
  PRIMARY KEY (`Customers_id_Customer`, `Orders_id_Order`),
  INDEX `fk_Fittings_Orders1_idx` (`Orders_id_Order` ASC),
  INDEX `fk_Fittings_Types_Of_Fitting1_idx` (`Types_Of_Fitting_id_Type_Of_Fitting` ASC),
  CONSTRAINT `fk_Fittings_Customers1`
    FOREIGN KEY (`Customers_id_Customer`)
    REFERENCES `main_database`.`Customers` (`id_Customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fittings_Orders1`
    FOREIGN KEY (`Orders_id_Order`)
    REFERENCES `main_database`.`Orders` (`id_Order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Fittings_Types_Of_Fitting1`
    FOREIGN KEY (`Types_Of_Fitting_id_Type_Of_Fitting`)
    REFERENCES `main_database`.`Types_Of_Fitting` (`id_Type_Of_Fitting`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Groups_Of_Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Groups_Of_Material` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Groups_Of_Material` (
  `id_Group_Of_Material` INT NOT NULL AUTO_INCREMENT COMMENT 'Id группы материалов',
  `Name_Of_Group` VARCHAR(80) NOT NULL COMMENT 'Наименование группы',
  PRIMARY KEY (`id_Group_Of_Material`),
  UNIQUE INDEX `Name_Of_Group_UNIQUE` (`Name_Of_Group` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Holidays`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Holidays` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Holidays` (
  `Employees_id_Employee` INT NOT NULL COMMENT 'Id сотрудинка\n',
  `Days_Of_Holidays` INT NOT NULL COMMENT 'Дни отпуска',
  `Days_In_Fact` INT NOT NULL COMMENT 'Дней по факту',
  `Rest_Of_Days` INT NOT NULL COMMENT 'Остаток дней\n',
  `Planned_Start` DATE NOT NULL COMMENT 'Запланированная дата начала отпуска',
  `In_Fact_Start` DATE NOT NULL COMMENT 'Фактическое начало отпуска',
  `In_Fact_End` DATE NOT NULL COMMENT 'Фактический конец',
  `Transfer` TINYINT NOT NULL COMMENT 'Перенос отпуска',
  `Cause_Transfer` VARCHAR(150) NULL COMMENT 'Причина переноса',
  `Year` YEAR(4) NOT NULL COMMENT 'Год',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  PRIMARY KEY (`Employees_id_Employee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Materials` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Materials` (
  `Vendor_Code` INT NOT NULL COMMENT 'Артикул',
  `Name_Of_Material` VARCHAR(80) NOT NULL COMMENT 'Наименование материала',
  `Cost_Of_Material` FLOAT NOT NULL COMMENT 'Цена материала',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  `Photo` MEDIUMBLOB NULL DEFAULT NULL COMMENT 'Фото',
  `Units_id_Unit` INT NOT NULL COMMENT 'Единица измерения',
  `Groups_Of_Material_id_Group_Of_Material` INT NOT NULL COMMENT 'Группа материала',
  `Types_Of_Material_id_Type_Of_Material` INT NOT NULL COMMENT 'Тип материала',
  `Countries_id_Country` INT NOT NULL COMMENT 'Страна-производитель',
  PRIMARY KEY (`Vendor_Code`),
  UNIQUE INDEX `Name_Of_Material_UNIQUE` (`Name_Of_Material` ASC),
  UNIQUE INDEX `Vendor_Code_UNIQUE` (`Vendor_Code` ASC),
  INDEX `fk_Materials_Units1_idx` (`Units_id_Unit` ASC),
  INDEX `fk_Materials_Group_Of_Material1_idx` (`Groups_Of_Material_id_Group_Of_Material` ASC),
  INDEX `fk_Materials_Types_Of_Material1_idx` (`Types_Of_Material_id_Type_Of_Material` ASC),
  INDEX `fk_Materials_Countries1_idx` (`Countries_id_Country` ASC),
  CONSTRAINT `fk_Materials_Units1`
    FOREIGN KEY (`Units_id_Unit`)
    REFERENCES `main_database`.`Units` (`id_Unit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Group_Of_Material1`
    FOREIGN KEY (`Groups_Of_Material_id_Group_Of_Material`)
    REFERENCES `main_database`.`Groups_Of_Material` (`id_Group_Of_Material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Types_Of_Material1`
    FOREIGN KEY (`Types_Of_Material_id_Type_Of_Material`)
    REFERENCES `main_database`.`Types_Of_Material` (`id_Type_Of_Material`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_Countries1`
    FOREIGN KEY (`Countries_id_Country`)
    REFERENCES `main_database`.`Countries` (`id_Country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Order_Channels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Order_Channels` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Order_Channels` (
  `id_Channel` INT NOT NULL AUTO_INCREMENT COMMENT 'Id канала заказа',
  `Name_of_channel` VARCHAR(80) NOT NULL COMMENT 'Наименование канала заказа\n',
  PRIMARY KEY (`id_Channel`),
  UNIQUE INDEX `id_UNIQUE` (`id_Channel` ASC),
  UNIQUE INDEX `Name_of_channel_UNIQUE` (`Name_of_channel` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Orders` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Orders` (
  `id_Order` INT NOT NULL AUTO_INCREMENT COMMENT 'Id заказа',
  `Date_Of_Order` DATE NOT NULL COMMENT 'Дата заказа',
  `Discount_Per_Cent` FLOAT NULL COMMENT '% скидки',
  `Paid` FLOAT NULL COMMENT 'Оплачено',
  `Debt` FLOAT NULL COMMENT 'Долг',
  `Date_Of_Delievery` DATE NULL COMMENT 'Дата сдачи заказа',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  `Types_Of_Order_id_Type_Of_Order` INT NOT NULL COMMENT 'Тип заказа',
  `Statuses_Of_Order_id_Status_Of_Order` INT NOT NULL COMMENT 'Статус заказа',
  `Products_id_Product` INT NOT NULL COMMENT 'Изделия',
  `Customers_id_Customer` INT NOT NULL COMMENT 'Клиент',
  `Responsible` VARCHAR(60) NOT NULL COMMENT 'Ответственный\n',
  `Executor` VARCHAR(60) NOT NULL COMMENT 'Выполнил',
  PRIMARY KEY (`id_Order`),
  INDEX `fk_Orders_Types_Of_Order1_idx` (`Types_Of_Order_id_Type_Of_Order` ASC),
  INDEX `fk_Orders_Statuses_Of_Order1_idx` (`Statuses_Of_Order_id_Status_Of_Order` ASC),
  INDEX `fk_Orders_Products1_idx` (`Products_id_Product` ASC),
  INDEX `fk_Orders_Customers1_idx` (`Customers_id_Customer` ASC),
  INDEX `fk_Orders_Employees1_idx` (`Responsible` ASC),
  INDEX `fk_Orders_Employees2_idx` (`Executor` ASC),
  CONSTRAINT `fk_Orders_Types_Of_Order1`
    FOREIGN KEY (`Types_Of_Order_id_Type_Of_Order`)
    REFERENCES `main_database`.`Types_Of_Order` (`id_Type_Of_Order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Statuses_Of_Order1`
    FOREIGN KEY (`Statuses_Of_Order_id_Status_Of_Order`)
    REFERENCES `main_database`.`Statuses_Of_Order` (`id_Status_Of_Order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Products1`
    FOREIGN KEY (`Products_id_Product`)
    REFERENCES `main_database`.`Products` (`id_Product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Customers1`
    FOREIGN KEY (`Customers_id_Customer`)
    REFERENCES `main_database`.`Customers` (`id_Customer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Employees1`
    FOREIGN KEY (`Responsible`)
    REFERENCES `main_database`.`Employees` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Employees2`
    FOREIGN KEY (`Executor`)
    REFERENCES `main_database`.`Employees` (`Login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Payment_States`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Payment_States` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Payment_States` (
  `id_Payment_States` INT NOT NULL AUTO_INCREMENT COMMENT 'Id статуса оплаты',
  `Name_Of_State` VARCHAR(45) NOT NULL COMMENT 'Наименование статуса оплаты',
  PRIMARY KEY (`id_Payment_States`),
  UNIQUE INDEX `id_Payment_States_UNIQUE` (`id_Payment_States` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Payrolls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Payrolls` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Payrolls` (
  `Employees_id_Employee` INT NOT NULL COMMENT 'Id сотрудника',
  `Date_Of_Pay` DATE NOT NULL COMMENT 'Дата выплаты',
  `Salary` FLOAT NOT NULL COMMENT 'Оклад',
  `Piece-work_Payment` FLOAT NULL COMMENT 'Сдельная оплата',
  `Accrual_Period_Start` DATE NOT NULL COMMENT 'Начало периода начисления',
  `Accural_Period_End` DATE NOT NULL COMMENT 'Конец периода начисления',
  `Penalty` FLOAT NULL COMMENT 'Вычеты',
  `Total_Salary` FLOAT NOT NULL COMMENT 'Общая сумма з/п',
  `To_Pay` FLOAT NOT NULL COMMENT 'К выплате',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  `id_Document_Of_Consumption` INT NOT NULL COMMENT 'Документ расхода',
  PRIMARY KEY (`Employees_id_Employee`),
  INDEX `fk_Payrolls_Documents_Of_Сonsumption1_idx` (`id_Document_Of_Consumption` ASC),
  CONSTRAINT `fk_Payrolls_Documents_Of_Сonsumption1`
    FOREIGN KEY (`id_Document_Of_Consumption`)
    REFERENCES `main_database`.`Documents_Of_Consumption` (`id_Document_Of_Consumption`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Periodicities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Periodicities` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Periodicities` (
  `id_Periodicity` INT NOT NULL AUTO_INCREMENT COMMENT 'Id периодичности',
  `Name_Of_Periodicity` VARCHAR(60) NOT NULL COMMENT 'Наименование периодичности',
  PRIMARY KEY (`id_Periodicity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Products` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Products` (
  `id_Product` INT NOT NULL AUTO_INCREMENT COMMENT 'Id изделия',
  `Table_Materials_To_Product_idTable_Materials_To_Product` INT NOT NULL COMMENT 'Тч материалов для изделия',
  `Fixed_Price` FLOAT NOT NULL COMMENT 'Фиксированная стоиомость',
  `Per_Cents` FLOAT NULL COMMENT '% от продажной стоиомости',
  `Added_Price_For_Complexity` FLOAT NULL COMMENT 'Дополнительная стоиомость за сложность',
  `Description` VARCHAR(150) NULL COMMENT 'Описание изделия',
  `Photo` MEDIUMBLOB NULL DEFAULT NULL COMMENT 'Фото',
  PRIMARY KEY (`id_Product`),
  UNIQUE INDEX `id_Product_UNIQUE` (`id_Product` ASC),
  INDEX `fk_Products_Table_Materials_To_Product1_idx` (`Table_Materials_To_Product_idTable_Materials_To_Product` ASC),
  CONSTRAINT `fk_Products_Table_Materials_To_Product1`
    FOREIGN KEY (`Table_Materials_To_Product_idTable_Materials_To_Product`)
    REFERENCES `main_database`.`Table_Materials_To_Product` (`idTable_Materials_To_Product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Receipt_Of_Materials`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Receipt_Of_Materials` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Receipt_Of_Materials` (
  `Documents_Of_Receipts_id_Document_Of_Receipt` INT NOT NULL COMMENT 'Документ',
  `Coming_Date` DATE NOT NULL COMMENT 'Дата поступления',
  `Summ` FLOAT NOT NULL COMMENT 'Сумма прихода',
  `Notes` VARCHAR(150) NULL COMMENT 'Доп сведения',
  `Payment_States_id_Payment_States` INT NOT NULL COMMENT 'Статус оплаты',
  `Type_Of_Transactions_id_Type_Of_Transaction` INT NOT NULL COMMENT 'Тип операции',
  `Suppliers_id_Supplier` INT NOT NULL COMMENT 'Поставщик',
  INDEX `fk_Receipt_Of_Materials_Payment_States1_idx` (`Payment_States_id_Payment_States` ASC),
  INDEX `fk_Receipt_Of_Materials_Type_Of_Transactions1_idx` (`Type_Of_Transactions_id_Type_Of_Transaction` ASC),
  INDEX `fk_Receipt_Of_Materials_Suppliers1_idx` (`Suppliers_id_Supplier` ASC),
  PRIMARY KEY (`Documents_Of_Receipts_id_Document_Of_Receipt`),
  CONSTRAINT `fk_Receipt_Of_Materials_Payment_States1`
    FOREIGN KEY (`Payment_States_id_Payment_States`)
    REFERENCES `main_database`.`Payment_States` (`id_Payment_States`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipt_Of_Materials_Type_Of_Transactions1`
    FOREIGN KEY (`Type_Of_Transactions_id_Type_Of_Transaction`)
    REFERENCES `main_database`.`Type_Of_Transactions` (`id_Type_Of_Transaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipt_Of_Materials_Suppliers1`
    FOREIGN KEY (`Suppliers_id_Supplier`)
    REFERENCES `main_database`.`Suppliers` (`id_Supplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipt_Of_Materials_Documents_Of_Receipts1`
    FOREIGN KEY (`Documents_Of_Receipts_id_Document_Of_Receipt`)
    REFERENCES `main_database`.`Documents_Of_Receipts` (`id_Document_Of_Receipt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Statuses_Of_Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Statuses_Of_Order` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Statuses_Of_Order` (
  `id_Status_Of_Order` INT NOT NULL AUTO_INCREMENT COMMENT 'Id статуса заказа\n',
  `Name_Of_Status` VARCHAR(45) NOT NULL COMMENT 'Наименование статуса заказа',
  PRIMARY KEY (`id_Status_Of_Order`),
  UNIQUE INDEX `Name_Of_Status_UNIQUE` (`Name_Of_Status` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Store` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Store` (
  `Materials_Vendor_Code` INT NOT NULL COMMENT 'Артикул',
  `Count` FLOAT NOT NULL COMMENT 'Количество на складе',
  PRIMARY KEY (`Materials_Vendor_Code`),
  UNIQUE INDEX `Materials_Vendor_Code_UNIQUE` (`Materials_Vendor_Code` ASC),
  CONSTRAINT `fk_Store_Materials1`
    FOREIGN KEY (`Materials_Vendor_Code`)
    REFERENCES `main_database`.`Materials` (`Vendor_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Suppliers` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Suppliers` (
  `id_Supplier` INT NOT NULL AUTO_INCREMENT COMMENT 'Id поставщика',
  `Name_Of_Supplier` VARCHAR(100) NOT NULL COMMENT 'Имя поставщика\n',
  PRIMARY KEY (`id_Supplier`),
  UNIQUE INDEX `id_Supplier_UNIQUE` (`id_Supplier` ASC),
  UNIQUE INDEX `Name_Of_Supplier_UNIQUE` (`Name_Of_Supplier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Table_Materials_To_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Table_Materials_To_Product` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Table_Materials_To_Product` (
  `idTable_Materials_To_Product` INT NOT NULL COMMENT 'Id тч материалов для изделия',
  `Count` FLOAT NOT NULL COMMENT 'Количество материала',
  `Materials_Vendor_Code` INT NOT NULL COMMENT 'Артикул материала',
  PRIMARY KEY (`idTable_Materials_To_Product`),
  UNIQUE INDEX `idTable_Materials_To_Product_UNIQUE` (`idTable_Materials_To_Product` ASC),
  INDEX `fk_Table_Materials_To_Product_Materials1_idx` (`Materials_Vendor_Code` ASC),
  CONSTRAINT `fk_Table_Materials_To_Product_Materials1`
    FOREIGN KEY (`Materials_Vendor_Code`)
    REFERENCES `main_database`.`Materials` (`Vendor_Code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Type_Of_Transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Type_Of_Transactions` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Type_Of_Transactions` (
  `id_Type_Of_Transaction` INT NOT NULL AUTO_INCREMENT COMMENT 'Id типа операции',
  `Name_Of_Type` VARCHAR(45) NOT NULL COMMENT 'Наименование типа операции',
  PRIMARY KEY (`id_Type_Of_Transaction`),
  UNIQUE INDEX `id_Type_Of_Transaction_UNIQUE` (`id_Type_Of_Transaction` ASC),
  UNIQUE INDEX `Name_Of_Type_UNIQUE` (`Name_Of_Type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Types_Of_Fitting`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Types_Of_Fitting` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Types_Of_Fitting` (
  `id_Type_Of_Fitting` INT NOT NULL AUTO_INCREMENT COMMENT 'Id типа примерки',
  `Name_Of_type` VARCHAR(45) NOT NULL COMMENT 'Наименование типа примерки',
  PRIMARY KEY (`id_Type_Of_Fitting`),
  UNIQUE INDEX `Name_Of_type_UNIQUE` (`Name_Of_type` ASC),
  UNIQUE INDEX `id_Type_Of_Fitting_UNIQUE` (`id_Type_Of_Fitting` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Types_Of_Material`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Types_Of_Material` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Types_Of_Material` (
  `id_Type_Of_Material` INT NOT NULL AUTO_INCREMENT COMMENT 'Id типа материала',
  `Name_Of_Type` VARCHAR(45) NOT NULL COMMENT 'Наименование типа',
  PRIMARY KEY (`id_Type_Of_Material`),
  UNIQUE INDEX `Name_Of_Type_UNIQUE` (`Name_Of_Type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Types_Of_Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Types_Of_Order` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Types_Of_Order` (
  `id_Type_Of_Order` INT NOT NULL AUTO_INCREMENT COMMENT 'Id типа заказа',
  `Name_Of_Type` VARCHAR(80) NOT NULL COMMENT 'Наименование типа заказа',
  PRIMARY KEY (`id_Type_Of_Order`),
  UNIQUE INDEX `Name_Of_Type_UNIQUE` (`Name_Of_Type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Types_Of_Payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Types_Of_Payment` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Types_Of_Payment` (
  `id_Of_Type` INT NOT NULL AUTO_INCREMENT COMMENT 'Id формы оплаты',
  `Name_Of_Type` VARCHAR(45) NOT NULL COMMENT 'Наименование формы',
  PRIMARY KEY (`id_Of_Type`),
  UNIQUE INDEX `Name_Of_Type_UNIQUE` (`Name_Of_Type` ASC),
  UNIQUE INDEX `id_Of_Type_UNIQUE` (`id_Of_Type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `main_database`.`Units`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `main_database`.`Units` ;

CREATE TABLE IF NOT EXISTS `main_database`.`Units` (
  `id_Unit` INT NOT NULL AUTO_INCREMENT COMMENT 'Id единицы измерения',
  `Name_Of_Unit` VARCHAR(80) NOT NULL COMMENT 'Наименование единицы',
  PRIMARY KEY (`id_Unit`),
  UNIQUE INDEX `Name_Of_Unit_UNIQUE` (`Name_Of_Unit` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
